Geant2txt_int: Geant2txt_int.o 
	gcc -o Geant2txt_int Geant2txt_int.o -lm
Geant2txt_int.o: Geant2txt_int.c
	gcc -c Geant2txt_int.c

clean:
	rm  Geant2txt_int Geant2txt_int.o  -r data -r results -r sino
	mkdir data
	mkdir results
	mkdir sino
# end of Makefile

